version: '3'
services:
  
  harness:
    restart: always
    image: actionml/harness:develop
    container_name: harness
    ports:
      - "9090:9090"
    environment:
      MONGO_URI: mongodb://mongo:27017
      HARNESS_URI: http://0.0.0.0:9090
      ELASTICSEARCH_URI: https://vpc-elastic-search-domain-dev-eqeatv2dgc5nc6ay3jwwb2ncgi.us-east-1.es.amazonaws.com
    depends_on:
      - mongo
    volumes:
      - ${HARNESS_LOGS}:/harness/logs
      - ${HARNESS_DATA}:/data
      
  mongo:
    restart: always
    image: mongo:4.2
    container_name: mongo
    command: --logappend --logpath=/tmp/mongod.log
    ports:
      - "27017:27017"
    volumes:
      - ${MONGO_LOGS}:/logs
      - ${MONGO_DATA}:/data/db

  harness-cli:
    restart: always
    image: actionml/harness-cli:develop
    container_name: harness-cli
    environment:
        HARNESS_SERVER_ADDRESS: harness
    volumes:
    - ${HARNESS_DATA}:/data
    - ./ur.json:/ur.json
    - ./ur-2.json:/ur-2.json

  watchtower:
    restart: always
    image: v2tec/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 3000
